USE sql_learning;

DROP TABLE IF EXISTS CHUYENBAY;
DROP TABLE IF EXISTS LAMVIEC;
DROP TABLE IF EXISTS MAYBAY;
DROP TABLE IF EXISTS LOAIMAYBAY;
DROP TABLE IF EXISTS PHICONG;
DROP TABLE IF EXISTS CONGTY;
DROP TABLE IF EXISTS Caidat;
DROP TABLE IF EXISTS Khuvuc;
DROP TABLE IF EXISTS Loai;
DROP TABLE IF EXISTS May;
DROP TABLE IF EXISTS Phanmen;
DROP TABLE IF EXISTS phong;